import mongoose from 'mongoose';

const plainObject = { type: mongoose.Schema.Types.Mixed, default: {} };

const characterSchema = new mongoose.Schema({
  user: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  system: { type: String, enum: ['vampire', 'dnd'], default: 'vampire', index: true },

  // Campos comuns
  name: { type: String, required: true, trim: true },
  player: { type: String, default: '' },
  chronicle: { type: String, default: '' },
  concept: { type: String, default: '' },
  notes: { type: String, default: '' },
  history: { type: String, default: '' },
  attributes: plainObject,
  skills: plainObject,

  // Vampiro: A Máscara 5e
  ambition: { type: String, default: '' },
  desire: { type: String, default: '' },
  sire: { type: String, default: '' },
  cult: { type: String, default: '' },
  clan: { type: String, default: '' },
  predator: { type: String, default: '' },
  generation: { type: String, default: '' },
  resonance: { type: String, default: '' },
  bloodPotency: { type: Number, default: 1, min: 0, max: 10 },
  bloodSurge: { type: String, default: '' },
  mendAmount: { type: String, default: '' },
  powerBonus: { type: String, default: '' },
  rouseReroll: { type: String, default: '' },
  feedingPenalty: { type: String, default: '' },
  baneSeverity: { type: String, default: '' },
  humanity: { type: Number, default: 7, min: 0, max: 10 },
  hunger: { type: Number, default: 1, min: 0, max: 5 },
  health: { current: { type: Number, default: 0 }, max: { type: Number, default: 0 } },
  willpower: { current: { type: Number, default: 0 }, max: { type: Number, default: 0 } },
  disciplines: [{ name: String, level: Number, powers: [String], notes: String, source: String }],
  backgrounds: [{ name: String, value: Number, notes: String }],
  advantages: [{ name: String, value: Number, notes: String }],
  disadvantages: [{ name: String, value: Number, notes: String }],
  convictions: [{ name: String, value: Number, notes: String }],
  tenets: { type: String, default: '' },
  convictionText: { type: String, default: '' },
  clanBane: { type: String, default: '' },
  advantageText: { type: String, default: '' },
  flawText: { type: String, default: '' },
  equipment: { type: String, default: '' },
  coterie: { type: String, default: '' },
  relationshipMap: { type: String, default: '' },
  rituals: { type: String, default: '' },
  thinBloodAlchemy: { type: String, default: '' },
  trueAge: { type: String, default: '' },
  apparentAge: { type: String, default: '' },
  birthDate: { type: String, default: '' },
  deathDate: { type: String, default: '' },
  appearance: { type: String, default: '' },
  distinguishingFeatures: { type: String, default: '' },
  experienceTotal: { type: String, default: '' },
  experienceSpent: { type: String, default: '' },

  // D&D 5e
  race: { type: String, default: '' },
  characterClass: { type: String, default: '' },
  level: { type: Number, default: 1, min: 1, max: 20 },
  background: { type: String, default: '' },
  alignment: { type: String, default: '' },
  experience: { type: String, default: '' },
  savingThrows: plainObject,
  inspiration: { type: String, default: '' },
  proficiencyBonus: { type: String, default: '' },
  armorClass: { type: String, default: '' },
  initiative: { type: String, default: '' },
  speed: { type: String, default: '' },
  hitPointsMax: { type: String, default: '' },
  hitPoints: { type: String, default: '' },
  tempHitPoints: { type: String, default: '' },
  hitDice: { type: String, default: '' },
  deathSaveSuccesses: { type: Number, default: 0, min: 0, max: 3 },
  deathSaveFailures: { type: Number, default: 0, min: 0, max: 3 },
  passivePerception: { type: String, default: '' },
  attacks: { type: String, default: '' },
  personalityTraits: { type: String, default: '' },
  ideals: { type: String, default: '' },
  bonds: { type: String, default: '' },
  flaws: { type: String, default: '' },
  features: { type: String, default: '' },
  age: { type: String, default: '' },
  height: { type: String, default: '' },
  weight: { type: String, default: '' },
  eyes: { type: String, default: '' },
  skin: { type: String, default: '' },
  hair: { type: String, default: '' },
  allies: { type: String, default: '' },
  additionalFeatures: { type: String, default: '' },
  treasures: { type: String, default: '' },
  spellcastingClass: { type: String, default: '' },
  spellcastingAbility: { type: String, default: '' },
  spellSaveDc: { type: String, default: '' },
  spellAttackBonus: { type: String, default: '' },
  cantrips: { type: String, default: '' },
  spells: { type: String, default: '' },

  // Extensão para sistemas futuros e templates personalizados.
  details: { type: mongoose.Schema.Types.Mixed, default: {} },
  templatePreferences: { type: mongoose.Schema.Types.Mixed, default: {} },
}, { timestamps: true, strict: true });

export default mongoose.model('CharacterSheet', characterSchema);
