import { Router } from 'express';
import { protect } from '../middleware/auth.js';
import { createCharacter, deleteCharacter, getCharacter, listCharacters, updateCharacter } from '../controllers/characterController.js';
const router = Router();
router.use(protect);
router.get('/', listCharacters);
router.post('/', createCharacter);
router.get('/:id', getCharacter);
router.put('/:id', updateCharacter);
router.delete('/:id', deleteCharacter);
export default router;
