export const dndPages = [
  {
    id: 'home',
    path: '/dnd',
    title: 'D&D 5e',
    menuLabel: 'Início D&D',
    type: 'systemHome',
    showInMenu: true,
    order: 0,
  },
  {
    id: 'criacao-personagens',
    path: '/dnd/criacao',
    title: 'Criação de Personagens | D&D 5e',
    menuLabel: 'Criação de Personagens',
    type: 'article',
    component: 'CriacaoPersonagens',
    showInMenu: true,
    order: 10,
  },
  {
    id: 'classes',
    path: '/dnd/classes',
    title: 'Classes | D&D 5e',
    menuLabel: 'Classes',
    type: 'construction',
    showInMenu: true,
    order: 20,
  },
  {
    id: 'racas',
    path: '/dnd/racas',
    title: 'Raças | D&D 5e',
    menuLabel: 'Raças',
    type: 'construction',
    showInMenu: true,
    order: 30,
  },
  {
    id: 'antecedentes',
    path: '/dnd/antecedentes',
    title: 'Antecedentes | D&D 5e',
    menuLabel: 'Antecedentes',
    type: 'construction',
    showInMenu: true,
    order: 40,
  },
  {
    id: 'equipamentos',
    path: '/dnd/equipamentos',
    title: 'Equipamentos | D&D 5e',
    menuLabel: 'Equipamentos',
    type: 'construction',
    showInMenu: true,
    order: 50,
  },
  {
    id: 'magias',
    path: '/dnd/magias',
    title: 'Magias | D&D 5e',
    menuLabel: 'Magias',
    type: 'construction',
    showInMenu: true,
    order: 60,
  },
  {
    id: 'regras',
    path: '/dnd/regras',
    title: 'Regras | D&D 5e',
    menuLabel: 'Regras',
    type: 'construction',
    showInMenu: true,
    order: 70,
  },
  {
    id: 'monge',
    path: '/dnd/monge',
    title: 'Como criar um Monge | D&D 5e',
    menuLabel: 'Monge',
    type: 'article',
    component: 'Monge',
    showInMenu: true,
    order: 80,
  },
  {
    id: 'exemplo-monge-tiefling',
    path: '/dnd/hadria',
    title: 'Exemplo de ficha de um Monge | D&D 5e',
    menuLabel: 'Exemplo: Monge Tiefling',
    type: 'article',
    component: 'ExemploHadria',
    showInMenu: true,
    order: 90,
  },
  {
    id: 'monstros',
    path: '/dnd/monstros',
    title: 'Monstros | D&D 5e',
    menuLabel: 'Monstros',
    type: 'construction',
    showInMenu: true,
    order: 100,
  },
];
