import React from 'react';
import { useEffect, useState } from 'react';import { useNavigate, useParams } from 'react-router-dom';import DotInput from '../components/DotInput.jsx';import { api } from '../services/api.js';import { attributes, clans, disciplines, predators, skills } from '../data/reference.js';
const empty={name:'',player:'',chronicle:'',concept:'',ambition:'',desire:'',clan:'',predator:'',generation:'',bloodPotency:1,humanity:7,hunger:1,health:{current:3,max:3},willpower:{current:3,max:3},attributes:{},skills:{},disciplines:[],advantages:[],flaws:[],convictions:[],coterie:'',notes:'',history:''};
export default function CharacterForm(){const {id}=useParams();const nav=useNavigate();const [form,setForm]=useState(empty);useEffect(()=>{if(id)api.get('/characters/'+id).then(r=>setForm({...empty,...r.data,attributes:r.data.attributes||{},skills:r.data.skills||{}}))},[id]);function set(k,v){setForm({...form,[k]:v})}function setDot(group,k,v){setForm({...form,[group]:{...form[group],[k]:v}})}async function submit(e){e.preventDefault();const {data}=id?await api.put('/characters/'+id,form):await api.post('/characters',form);nav('/fichas/'+data._id)}
return <form className="card sheet" onSubmit={submit}><h1>{id?'Editar ficha':'Nova ficha'}</h1><div className="columns"><input placeholder="Nome" value={form.name} onChange={e=>set('name',e.target.value)} required/><input placeholder="Jogador" value={form.player} onChange={e=>set('player',e.target.value)}/><input placeholder="Crônica" value={form.chronicle} onChange={e=>set('chronicle',e.target.value)}/><input placeholder="Conceito" value={form.concept} onChange={e=>set('concept',e.target.value)}/><input placeholder="Ambição" value={form.ambition} onChange={e=>set('ambition',e.target.value)}/><input placeholder="Desejo" value={form.desire} onChange={e=>set('desire',e.target.value)}/><select value={form.clan} onChange={e=>set('clan',e.target.value)}><option>Clã</option>{clans.map(x=><option key={x}>{x}</option>)}</select><select value={form.predator} onChange={e=>set('predator',e.target.value)}><option>Predador</option>{predators.map(x=><option key={x}>{x}</option>)}</select><input placeholder="Geração" value={form.generation} onChange={e=>set('generation',e.target.value)}/></div>
<h2>Atributos</h2><div className="dot-grid">{attributes.map(a=><DotInput key={a} label={a} value={form.attributes?.[a]||0} onChange={v=>setDot('attributes',a,v)}/>)}</div>
<h2>Perícias</h2><div className="dot-grid">{skills.map(s=><DotInput key={s} label={s} value={form.skills?.[s]||0} onChange={v=>setDot('skills',s,v)}/>)}</div>
<h2>Marcadores</h2><div className="columns small"><label>Potência<input type="number" min="0" max="10" value={form.bloodPotency} onChange={e=>set('bloodPotency',+e.target.value)}/></label><label>Humanidade<input type="number" min="0" max="10" value={form.humanity} onChange={e=>set('humanity',+e.target.value)}/></label><label>Fome<input type="number" min="0" max="5" value={form.hunger} onChange={e=>set('hunger',+e.target.value)}/></label></div>
<h2>Disciplinas</h2><textarea value={form.disciplineText||''} placeholder={`Exemplo:\n${disciplines[0]} 2 - poderes escolhidos`} onChange={e=>set('disciplineText',e.target.value)} />
<h2>Vantagens, defeitos, convicções e história</h2><textarea placeholder="Vantagens" value={form.advantageText||''} onChange={e=>set('advantageText',e.target.value)}/><textarea placeholder="Defeitos" value={form.flawText||''} onChange={e=>set('flawText',e.target.value)}/><textarea placeholder="Convicções e alicerces" value={form.convictionText||''} onChange={e=>set('convictionText',e.target.value)}/><textarea placeholder="Histórico" value={form.history} onChange={e=>set('history',e.target.value)}/><textarea placeholder="Notas" value={form.notes} onChange={e=>set('notes',e.target.value)}/><button className="primary">Salvar ficha</button></form>}
